### ISSUE TITLE
화면 디자인

### ISSUE THREAD

**Issue by Kimminwoo02** [Kimminwoo02/Team_Project#17]
파트별 화면 디자인

김민우 
* [ ] 메인페이지
* [ ] 매칭 페이지
* [ ] 시설현황

김예준
* [x] 아이디/비밀번호 찾기
* [x] 마이페이지
* [x] 히스토리
* [ ] 교통편

손용수
* [ ] 게시판
* [ ] 카테고리별 게시판
* [ ] 게시글

홍지혜
* [ ] 채팅
* [ ] 채팅방
* [ ] 알람

**Comment by Kimminwoo02** [comment]
완료되면 체크!

**Comment by MonsterEner** [comment]
Checked!
